import type { Metadata } from 'next';

import 'normalize.css';
import './globals.css';

import { DefaultLayout } from './components/default-layout';
import { Noto_Sans_JP } from 'next/font/google';

const noto = Noto_Sans_JP({
  weight: ['400', '600'],
  style: 'normal',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={noto.className}>
        <DefaultLayout>{children}</DefaultLayout>
      </body>
    </html>
  );
}
